services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    # command: gunicorn mmt.wsgi:application --bind 0.0.0.0:8000 --workers 1 --timeout 600
    command: hypercorn mmt.asgi:application --bind '0.0.0.0:8000'
    volumes:
      - static_volume:/home/app/web/staticfiles
      - user_files:/home/app/web/user_files
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    env_file:
      - ./.env.prod
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  mariadb_data:
  static_volume:
  user_files:
