services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn mmt.wsgi:application --bind 0.0.0.0:8000 --workers=1
    volumes:
      - db:/home/app/web/db
      - static_volume:/home/app/web/staticfiles
      - user_files:/home/app/web/user_files
    expose:
      - 8000
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  db:
  static_volume:
  user_files:
