# Generated by Django 5.1.3 on 2024-11-19 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload_jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadjob",
            name="check_media_files",
            field=models.BooleanField(default=False, verbose_name="Check media files"),
        ),
        migrations.AlterField(
            model_name="uploadjob",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="uploadjob",
            name="language",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Language"
            ),
        ),
        migrations.AlterField(
            model_name="uploadjob",
            name="make_available_on_platform",
            field=models.BooleanField(
                default=False, verbose_name="Make available on platform"
            ),
        ),
        migrations.AlterField(
            model_name="uploadjob",
            name="replace_existing_files",
            field=models.BooleanField(
                default=False, verbose_name="Replace existing files"
            ),
        ),
        migrations.AlterField(
            model_name="uploadjob",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="uploadjob",
            name="transcribe",
            field=models.BooleanField(default=False, verbose_name="Transcribe"),
        ),
        migrations.AlterField(
            model_name="uploadjob",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="upload_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
