# Generated by Django 5.1.2 on 2024-10-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadjob",
            name="options",
        ),
        migrations.AddField(
            model_name="uploadjob",
            name="check_media_files",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="uploadjob",
            name="language",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="uploadjob",
            name="make_available_on_platform",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="uploadjob",
            name="remarks",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="uploadjob",
            name="replace_existing_files",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="uploadjob",
            name="transcribe",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="UploadOptions",
        ),
    ]
