# Generated by Django 5.1.2 on 2024-10-13 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_uploadjob_remarks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedfile",
            name="job",
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="upload_job",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_files",
                to="core.uploadjob",
            ),
            preserve_default=False,
        ),
    ]
