# Generated by Django 5.1.3 on 2024-11-08 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_uploadedfile_job_uploadedfile_upload_job"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadjob",
            name="user",
        ),
        migrations.DeleteModel(
            name="UploadedFile",
        ),
        migrations.DeleteModel(
            name="UploadJob",
        ),
    ]
