# Generated by Django 5.1.3 on 2024-11-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploaded_files", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="size",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="transferred",
            field=models.BigIntegerField(default=0),
        ),
    ]
